version: "3.7"

services:
    alpaca-connector:
        env_file: .env
        build: karaf-base
        image: karaf-test/alpaca-connector
    
    activemq:
        image: oapass/activemq:20180618
        env_file: .env
        ports:
          - "8161:8161"


